#!/bin/bash

function cleanup() {
    rm -f "$i3_tmp_config"
}

cd "$(dirname "$0")"
source ./inputdevrc
source ../monitorsrc

# mouseaccel comes from dotfiles
mouseaccel off

i3_tmp_config=$(mktemp --tmpdir 'i3.config.XXXXXX')
trap cleanup EXIT
grep -v 'PRIMARYONLY' "$DOTFILE_DIR/i3/config" > "$i3_tmp_config"
export XORG_GAMING_SESSION='1'

disable_xorg_input_devices_on "$DISPLAY"
i3 --config "$i3_tmp_config" &
i3_pid="$!"
synergyc --name 'deathwing-gaming' --debug DEBUG --log /dev/stderr --no-daemon 127.0.0.1 &
synergyc_pid="$!"
wait "$i3_pid"
kill "$synergyc_pid"
