#!/bin/bash

# This script launches an alternate X server on my more
# powerful GPU for gaming.
#
# You likely need to create an /etc/X11/Xwrapper.config file
# and set `allowed_users = anybody` before this will work.

# Xorg configuration that runs the X server on the desired
# GPU for gaming.
gaming_xorg_conf='xorg.nvidia.conf'

gpu_device='0000:03:00.0'
gpu_audio_device='0000:03:00.1'

if sudo rmmod vfio_pci 2>&1 | grep -q 'in use'; then
    echo 'Failed to remove vfio_pci module, is the GPU in use?'
    exit 1
fi
if ! lsmod | grep -q 'nvidia'; then
    sudo bash <<EOF
        echo '' > /sys/bus/pci/devices/$gpu_device/driver_override
        echo '' > /sys/bus/pci/devices/$gpu_audio_device/driver_override
        modprobe nvidia
        modprobe nvidia_modeset
        modprobe nvidia_drm
EOF
fi

# Kill existing Synergy servers just in case there are some out there.
cd $(dirname "$0")
../single-monitor
xinit ./xorg-gaming-session -- :10 -config "$gaming_xorg_conf" -sharevts
./swap-input-to-primary
../dual-monitor
