#!/bin/bash

cd "$(dirname "$0")"
source ./inputdevrc

# mouseaccel comes from dotfiles
mouseaccel off

disable_xorg_input_devices_on "$DISPLAY"
feh --bg-center "$HOME/ownCloud/personal/data/wallpapers/space/WallpaperFusion-a-long-way-from-home-3840x1080-M2.jpg"
openbox
