#!/bin/bash

cd "$(dirname "$0")"
source monitorsrc

hdmi/hdmisw.py "$gaming_monitor_linux_hdmi_input"
# We have to wait for the monitor to be rediscovered by the GPU before adjusting
# the layout using xrandr.
sleep 3
xrandr --output "$gaming_monitor" --auto --"$gaming_monitor_position" "$primary_monitor"
