#!/bin/bash

lockfile='/var/run/lock/subsys/g810-colorscheme'
g810_led='g810-led'

blue='000066'
dark_gray='333333'
gray='666666'
green='006600'
light_blue='666699'
light_gray='aaaaaa'
orange='996300'
purple='8d00a6'
red='660000'
white='ffffff'
yellow='999900'

if ! mkdir "$lockfile" >/dev/null 2>&1; then
    echo "Could not acquire lock at $lockfile" >&2
    exit 1
fi

# Set default key color to light grey.
$g810_led -an "$gray"

$g810_led -kn logo "$blue"

$g810_led -gn fkeys "$light_blue"

for k in $(seq 0 9); do
    $g810_led -kn "$k" "$green"
done
$g810_led -gn numeric "$green"
$g810_led -kn numenter "$blue"

$g810_led -kn backspace "$red"
$g810_led -kn escape "$red"

for k in {shift,ctrl,meta,alt}_{left,right} menu capslock num_lock scroll_lock; do
    $g810_led -kn "$k" "$orange"
done

for k in w a s d; do
    $g810_led -kn "$k" "$yellow"
done
$g810_led -gn arrows "$yellow"

$g810_led -gn indicators "$light_gray"
$g810_led -gn multimedia "$purple"

for k in print_screen pause insert home page_up end page_down; do
    $g810_led -kn "$k" "$dark_gray"
done
$g810_led -kn delete "$red"

$g810_led -kn light "$white"
$g810_led -kn game "$white"
$g810_led -kn enter "$blue"

$g810_led -c

sleep 10
rm -rf "$lockfile"
