#!/bin/bash

remote_forward_port="$1"
if [[ -z "$remote_forward_port" ]]; then
    remote_forward_port=3333
fi

read -r -d '' HELP_PRIVATEKEY <<EOF
<< INSERT PRIVATE KEY HERE >>
EOF

HELP_DOMAIN='koelndorfer.com'
HELP_USER='remotehelp'
HELP_IDENTITYFILE="$HOME/.ssh/id_ecdsa_help"
SERVICE="$(hostname -s)"

function get_address_and_port {
    srv_record="$1"
    port_number="$(echo "$srv_record" | awk '{ print $3 }')"
    address="$(echo "$srv_record" | awk '{ print $4 }' | sed -r -e 's/\.$//')"
    echo "$address $port_number"
}

function get_srv_record {
    service="$1"
    protocol="$2"
    domain="$3"

    dig +short "_${service}._${protocol}.${domain}" SRV
}

function deploy_privatekey {
    private_key_dir="$(dirname "$HELP_IDENTITYFILE")"
    mkdir -p "$private_key_dir"
    chmod 700 "$private_key_dir"
    echo "$HELP_PRIVATEKEY" > "$HELP_IDENTITYFILE"
    chmod 600 "$HELP_IDENTITYFILE"
}

help_addr_info="$(get_address_and_port "$(get_srv_record "$SERVICE" 'help' "$HELP_DOMAIN")")"
help_addr="$(echo "$help_addr_info" | awk '{ print $1 }')"
help_port="$(echo "$help_addr_info" | awk '{ print $2 }')"

deploy_privatekey
ssh -i "$HELP_IDENTITYFILE" -p "$help_port" -l "$HELP_USER" -N -R "${remote_forward_port}:localhost:22" "$help_addr"
